name: Workflow to deploy the app

# Define when the workflow should be triggered

on:
  push:
    branches:
      - */*

# Define jobs for the workflow
jobs:
# Job: Build
  build:
    runs-on: alpine-latest
# Steps for the build job
    steps: 
      - name: upload pages
        uses: actions/upload-pages-artifact@v2
      - name: deploy pages
        uses: actions/deploy-pages@v3


permissions:
  contents: read
  pages: write
  id-token: write